<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Card;

/**
 * CardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardRepository extends \Doctrine\ORM\EntityRepository
{

    public function persist(Card $entity)
    {
        $this->_em->persist($entity);
    }

    public function save(Card $entity = null)
    {
        if($entity) $this->persist($entity);
        $this->_em->flush();
    }

    public function remove(Card $entity)
    {
        $this->_em->remove($entity);
        $this->_em->flush();
    }
}
