<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Deck;

/**
 * DeckRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeckRepository extends \Doctrine\ORM\EntityRepository
{

    public function persist(Deck $entity)
    {
        $this->_em->persist($entity);
    }

    public function save(Deck $entity = null)
    {
        if($entity) $this->persist($entity);
        $this->_em->flush();
    }

    public function remove(Deck $entity)
    {
        $this->_em->remove($entity);
        $this->_em->flush();
    }
}
