<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Player;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{

    public function persist(Player $entity)
    {
        $this->_em->persist($entity);
    }

    public function save(Player $entity = null)
    {
        if($entity) $this->persist($entity);
        $this->_em->flush();
    }

    public function remove(Player $entity)
    {
        $this->_em->remove($entity);
        $this->_em->flush();
    }
}
